<?php
header('Content-type: application/xml');
echo '<?xml version="1.0" encoding="UTF-8"?>';
echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">';
$blogs = Blog::getAll();
$blog = new Blog();
$blog->setID($blogs[count($blogs)-1]);
$blog->connect();
echo '<url>';
echo '<loc>http://netnevis.ir</loc>';
echo '<lastmod>'.date('c', $blog->getMoment()).'</lastmod>';
echo '<changefreq>daily</changefreq>';
echo '<priority>1.0</priority>';
echo '</url>';
echo '<url>';
echo '<loc>http://netnevis.ir/about</loc>';
echo '<lastmod>'.date('c', $blog->getMoment()).'</lastmod>';
echo '<changefreq>monthly</changefreq>';
echo '<priority>1.0</priority>';
echo '</url>';
echo '<url>';
echo '<loc>http://netnevis.ir/ads</loc>';
echo '<lastmod>'.date('c', $blog->getMoment()).'</lastmod>';
echo '<changefreq>monthly</changefreq>';
echo '<priority>1.0</priority>';
echo '</url>';
echo '<url>';
echo '<loc>http://netnevis.ir/contact</loc>';
echo '<lastmod>'.date('c', $blog->getMoment()).'</lastmod>';
echo '<changefreq>monthly</changefreq>';
echo '<priority>1.0</priority>';
echo '</url>';
echo '<url>';
echo '<loc>http://netnevis.ir/terms</loc>';
echo '<lastmod>'.date('c', $blog->getMoment()).'</lastmod>';
echo '<changefreq>monthly</changefreq>';
echo '<priority>1.0</priority>';
echo '</url>';
echo '<url>';
echo '<loc>http://netnevis.ir/help</loc>';
echo '<lastmod>'.date('c', $blog->getMoment()).'</lastmod>';
echo '<changefreq>monthly</changefreq>';
echo '<priority>1.0</priority>';
echo '</url>';
echo '<url>';
echo '<loc>http://netnevis.ir/index</loc>';
echo '<lastmod>'.date('c', $blog->getMoment()).'</lastmod>';
echo '<changefreq>daily</changefreq>';
echo '<priority>1.0</priority>';
echo '</url>';
echo '</urlset>';